-- ========================================
-- HYPRLOCK CONFIGURATION
-- Screen lock appearance and behavior
-- ========================================

-- Import global variables
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Source: $HOME/.config/hypr/config/variables.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("_HOME._config.hypr.config.variables")

-- ========================================
-- BACKGROUND SETTINGS
-- ========================================
-- TODO: manual review — unknown section 'background {' on line 12

-- ========================================
-- GENERAL SETTINGS
-- ========================================

-- TODO: manual review — unknown section 'input-field {' on line 36

-- TODO: manual review — unknown section 'label {' on line 63

-- TODO: manual review — unknown section 'label {' on line 75

-- TODO: manual review — unknown section 'label {' on line 87
hl.config({
    general = {
        no_fade_in = true,
        no_fade_out = true,
        hide_cursor = true,
        grace = 0,
        disable_loading_bar = true,
    },
    -- ========================================
    -- INPUT FIELD CONFIGURATION
    -- ========================================
    -- ========================================
    -- DISPLAY LABELS
    -- ========================================
    -- Date Display
    -- Time Display
    -- Music Status Display
})

