-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Source: ~/.config/hypr/binds.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("binds")
-- Source: ~/.config/hypr/input.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("input")

--###############
--## MONITORS ###
--###############

-- See https://wiki.hyprland.org/Configuring/Monitors/
hl.monitor({
    output = "",
    mode = "preferred",
    position = "auto",
    scale = "1",
})

--################
--## AUTOSTART ###
--################

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:

-- exec-once = $terminal
-- exec-once = nm-applet &
-- exec-once = waybar & hyprpaper & firefox
--exec-once = nmcli connection up unimib --ask

--############################
--## ENVIRONMENT VARIABLES ###
--############################

-- See https://wiki.hyprland.org/Configuring/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("AQ_DRM_DEVICES", "/dev/dri/card1")
hl.env("XDG_MENU_PREFIX", "arch-")

--####################
--## LOOK AND FEEL ###
--####################

-- Refer to https://wiki.hyprland.org/Configuring/Variables/

-- https://wiki.hyprland.org/Configuring/Variables/#general

hl.curve("myBezier", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.05 } } })
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 7,
    bezier = "myBezier",
})
hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 7,
    bezier = "default",
    style = "popin 80%",
})
hl.animation({
    leaf = "border",
    enabled = true,
    speed = 10,
    bezier = "default",
})
hl.animation({
    leaf = "borderangle",
    enabled = true,
    speed = 8,
    bezier = "default",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 7,
    bezier = "default",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 6,
    bezier = "default",
})

hl.window_rule({
    name = "windowrule-1",
    match = {
        title = "^(Picture-in-Picture)$",
    },
    float = true,
    pin = true,
    --sticky = on
    size = "640 360",
    move = "((monitor_w*1)-650) ((monitor_h*1)-370)",
    -- TODO: manual review — unmapped window rule action: "keep_aspect_ratio on"
})

hl.window_rule({
    name = "windowrule-2",
    match = {
        title = "^(Firefox)$",
    },
    float = true,
    size = "640 360",
})

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioStop", hl.dsp.exec_cmd("playerctl stop"), { locked = true })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })
hl.config({
    general = {
        gaps_in = 5,
        gaps_out = 20,
        border_size = 2,
        -- https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
        col = {
            active_border = "rgba(e300ffee)",
            inactive_border = "rgba(595959aa)",
        },
        -- Set to true enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,
        -- Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
        allow_tearing = false,
        no_focus_fallback = true,
        layout = "dwindle",
    },
    -- https://wiki.hyprland.org/Configuring/Variables/#decoration
    decoration = {
        rounding = 10,
        -- Change transparency of focused and unfocused windows
        active_opacity = 1.0,
        inactive_opacity = 1.0,
        --drop_shadow = true
        --shadow_range = 4
        --shadow_render_power = 3
        --col.shadow = rgba(1a1a1aee)
        -- https://wiki.hyprland.org/Configuring/Variables/#blur
        blur = {
            enabled = true,
            size = 3,
            passes = 1,
            vibrancy = 0.1696,
        },
    },
    -- https://wiki.hyprland.org/Configuring/Variables/#animations
    animations = {
        enabled = true,
        -- Default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
    },
    -- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    dwindle = {
        preserve_split = true,-- # You probably want this
    },
    -- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
    master = {
        new_status = "master",
    },
    -- https://wiki.hyprland.org/Configuring/Variables/#misc
    misc = {
        force_default_wallpaper = 0,-- # Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo = true,-- # If true disables the random hyprland logo / anime girl background. :(
    },
    --#############################
    --## WINDOWS AND WORKSPACES ###
    --#############################
    -- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
    -- See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules
    -- Example windowrule v1
    -- windowrule = float, ^(kitty)$
    --#############################
    --## WINDOWS AND WORKSPACES ###
    --#############################
    -- Float, pin, and size the PiP window
    --windowrulev2 = float, title:^(Picture-in-Picture)$
    --windowrulev2 = pin, title:^(Picture-in-Picture)$
    --windowrulev2 = size 800 450, title:^(Picture-in-Picture)$
    --windowrulev2 = move 100%-820 100%-470, title:^(Picture-in-Picture)$
    --
    --# Catch it by the initial title as well (to prevent tiling at birth)
    --windowrulev2 = float, initialTitle:^(Picture-in-Picture)$
    --windowrulev2 = pin, initialTitle:^(Picture-in-Picture)$
    --windowrulev2 = float, class:.*
    -- We give the rule a name (pip_rule) so the parser is happy
    -- Float and Pin Picture-in-Picture
    -- Fix for Firefox (which often uses "Firefox" as the class)
})

hl.on("hyprland.start", function()
    hl.exec_cmd("waybar & hyprpaper & kitty")
    hl.exec_cmd("swww-daemon & sleep 0.1 & sww img ~/Downloads/wallpaper2.jpg & wal -i ~/Downloads/wallpaper2.jpg")
    hl.exec_cmd("mako & systemctl --user start hyprpolkitagent")
end)

