--############
--## INPUT ###
--############

-- https://wiki.hyprland.org/Configuring/Variables/#input
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.device({
  name = "epic-mouse-v1",
  sensitivity = -0.5,
})

hl.config({
  input = {
    kb_layout = "us",
    kb_variant = "",
    kb_model = "",
    kb_options = "",
    kb_rules = "",
    follow_mouse = 1,
    sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.
    touchpad = {
      natural_scroll = false,
    },
  },
})
